# Site settings
title: Devcase Tecnologia Wiki
email: wiki@devcase.com.br
description: > # this means to ignore newlines until "baseurl:"
  Artigos com dicas para programadores
baseurl: "/wiki/" # the subpath of your site, e.g. /blog/
url: "http://www.devcase.com.br" # the base hostname & protocol for your site
#twitter_username: devcase
github_username:  devcase
language: pt

# Build settings
markdown: kramdown
